//! Core TEE types used by the SDK.
//!
//! These types are self-contained — the SDK has no dependency on any internal
//! domain crate. They are intentionally minimal: enough to carry attestation
//! data across API boundaries without pulling in infrastructure dependencies.

use chrono::{DateTime, Utc};
use ed25519_dalek::VerifyingKey;
use std::fmt;

/// 32-byte SHA-256 measurement of the enclave contents (MRENCLAVE).
///
/// MRENCLAVE is produced by the SGX hardware during enclave loading. It is a
/// cryptographic hash of every page of enclave code and data at load time.
/// Two enclave binaries compiled from different source, or the same source
/// compiled with different flags, will have different MRENCLAVE values.
///
/// In GuaranTEE, the platform verifies that the MRENCLAVE in the startup quote
/// matches the value recorded during the build step. This is the core security
/// invariant: it proves the response was produced by the exact binary that was
/// deployed.
///
/// # Example
///
/// ```rust,ignore
/// use guarantee::MrEnclave;
///
/// let bytes = [0xAB_u8; 32];
/// let mr = MrEnclave::new(bytes);
/// println!("MRENCLAVE: {mr}"); // hex-encoded, lowercase
/// assert_eq!(mr.as_bytes(), &bytes);
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct MrEnclave([u8; 32]);

impl MrEnclave {
    /// Create an `MrEnclave` from raw bytes.
    pub fn new(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Return a reference to the underlying 32-byte measurement.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for MrEnclave {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MrEnclave({})", self)
    }
}

/// Formats as lowercase hex (64 characters, no prefix).
impl fmt::Display for MrEnclave {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in &self.0 {
            write!(f, "{:02x}", byte)?;
        }
        Ok(())
    }
}

/// 32-byte hash of the enclave signing key (MRSIGNER).
///
/// MRSIGNER is derived from the RSA key used to sign the enclave with
/// `gramine-sgx-sign`. Unlike MRENCLAVE, it does not change when the enclave
/// binary is updated — only when the signing key changes.
///
/// This property is used for MRSIGNER-scoped state: secrets sealed under
/// MRSIGNER can be read by any enclave version signed with the same key,
/// enabling state to persist across redeployments.
///
/// # Example
///
/// ```rust,ignore
/// use guarantee::MrSigner;
///
/// let bytes = [0xCD_u8; 32];
/// let mr = MrSigner::new(bytes);
/// println!("MRSIGNER: {mr}"); // hex-encoded, lowercase
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct MrSigner([u8; 32]);

impl MrSigner {
    /// Create an `MrSigner` from raw bytes.
    pub fn new(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Return a reference to the underlying 32-byte signer hash.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for MrSigner {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MrSigner({})", self)
    }
}

/// Formats as lowercase hex (64 characters, no prefix).
impl fmt::Display for MrSigner {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in &self.0 {
            write!(f, "{:02x}", byte)?;
        }
        Ok(())
    }
}

/// The SGX attestation quote produced at enclave startup.
///
/// A `StartupQuote` binds the enclave's identity (MRENCLAVE + MRSIGNER) to the
/// ephemeral Ed25519 public key generated by [`EnclaveAttestor::initialize`].
/// It is served at `GET /.well-known/tee-attestation` so that any caller can
/// independently verify the full trust chain:
///
/// ```text
/// Intel SGX hardware
///   └─ signs the DCAP quote
///         └─ quote embeds MRENCLAVE + MRSIGNER + attested_public_key
///               └─ attested_public_key signs every HTTP response
/// ```
///
/// In dev mode (`GUARANTEE_ENCLAVE` not set), `raw_quote` is the placeholder
/// `b"DEV_MODE_QUOTE"` and MRENCLAVE/MRSIGNER are filled with `0xDE` bytes.
/// Dev-mode quotes are not verifiable against Intel's DCAP infrastructure.
///
/// # Fields
///
/// - `raw_quote` — raw DCAP quote bytes as returned by `/dev/attestation/quote`
/// - `mr_enclave` — enclave code measurement
/// - `mr_signer` — signing key measurement
/// - `attested_public_key` — the Ed25519 public key whose private counterpart
///   signs every HTTP response
/// - `produced_at` — UTC timestamp of quote generation
#[derive(Clone, Debug)]
pub struct StartupQuote {
    /// Raw DCAP quote bytes from `/dev/attestation/quote`.
    pub raw_quote: Vec<u8>,
    /// SHA-256 measurement of the enclave binary (MRENCLAVE).
    pub mr_enclave: MrEnclave,
    /// SHA-256 hash of the enclave signing key (MRSIGNER).
    pub mr_signer: MrSigner,
    /// The ephemeral Ed25519 public key attested by this quote.
    pub attested_public_key: VerifyingKey,
    /// UTC timestamp when the quote was produced.
    pub produced_at: DateTime<Utc>,
}
